### ISSUE TITLE
multiple values in one fvo or in seperate fvos?

### ISSUE THREAD

**Issue by VeronikaEngler** [wibarab/featuredb#21]
I think we discussed this before but unfortunately weʔre not sure anymore what we landed on: if for one feature and one dialect we have several realisations, is it better to create seperate fvos or put both/all realisations in one fvo?

**Comment by dasch124** [comment]
I think we haven't reached a conclusion yet  ;-) however I think we agreed on not mixing several sources into one fvo, which leaves us with cases where one source provides evidence for several realisations.

Probably having one fvo element for each source+feature value-combination is the clearest option (e.g. a note in the fvo would not be clearly attached to either of them) and probably the easiest one in terms of processing (since we don't have to deal with several different cases, right @charlymo) 

As far as I remember it was mainly a question of input efficiency - if that's not a trouble to you, then I'd go for 1:1

**Comment by dasch124** [comment]
I think in practice we go for one value per fvo, right @VeronikaEngler  ?
