### ISSUE TITLE
implement script to reorder FVO content to conform to the schema

### ISSUE THREAD

**Issue by dasch124** [wibarab/featuredb#25]
Currently the ODD requires the order to be:

* name
* bibl 
* placeName 
* lang 
* date 

afterwards optional elements in any number or order: 

* personGrp
* cit
* note

**Comment by dasch124** [comment]
untested draft in [082_scripts_xsl/fvo_apply_order.xsl](https://github.com/wibarab/featuredb/blob/main/082_scripts_xsl/fvo_apply_order.xsl)

**Comment by VeronikaEngler** [comment]
hello, are there any news on the script? I'm working on the validation of the pronoun-files and I could really use the script here

**Comment by dasch124** [comment]
@likeanga is on it – I should be able to update on it next Thursday

**Comment by likeanga** [comment]
I checked the .xsl, it additionally copied parts of the elements so that e.g. <personGrp> and xml:ids were included twice. This is because of missing tei namespace of the elements `<personGrp>` and `<note>`; the element <cit> was also copied twice because it is not listed under the excluded elements in line 27: 
Line 27 thus should be 
```<xsl:copy-of select="*[not(self::tei:name|self::tei:bibl|self::tei:placeName|self::tei:lang|self::tei:date|self::tei:personGrp|self::tei:note|self::tei:cit)]"/>```

**Comment by likeanga** [comment]
I updated line 27 and checked the script again with comments between - it behaves as it should.
